module.exports = {
  purge: {
    content: [
      "./pages/**/*.{js,ts,jsx,tsx}",
      "./components/**/*.{js,ts,jsx,tsx}",
      "./modules/**/*.{js,ts,jsx,tsx}",
      "./styles/**/*.{css, scss}",
    ],
  },
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./modules/**/*.{js,ts,jsx,tsx}",
    "./styles/**/*.{css, scss}",
  ],
  theme: {
    screens: {
      "sm-mobile": "200px",
      mobile: "576px",
      tablet: "768px",
      "lg-tablet": "840px",
      laptop: "1024px",
      "lg-laptop": "1192px",
      "xl-laptop": "1264px",
      desktop: "1440px",
      "xl-desktop": "1620px",
    },
    container: {
      padding: "1rem",
      center: true,
      screens: {
        mobile: "100%",
        tablet: "488px",
        laptop: "768px",
        desktop: "1192px",
        "xl-desktop": "1192px",
      },
    },
    colors: {
      black: "#000000",
      black80: "rgba(0, 0, 0, 0.8)",
      black50: "rgba(0, 0, 0, 0.5)",
      black20: "rgba(0, 0, 0, 0.2)",
      grey: "#707070",
      white: "#ffffff",
      yellow: "#E7C36F",
      danger: "#FF453A",
      "brown-med": "#f3eee7",
    },
    fontFamily: {
      lexend: ['"Lexend Mega"'],
      noir: ['"Noir No 1"'],
    },
    fontSize: {
      body: ["16px"],
      subtitle: ["18px"],
      h6: ["18px"],
      h5: ["22px"],
      h3: ["33px"],
      h2: ["37px"],
      h4: ["25px"],
      h1: ["45px"],
    },
  },
  plugins: [],
};
